name: get cca
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: 'a版本号'
        required: false
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: Yakov5776/gh-apkmirror-dl@v1.3
      with:
        org: 'king'
        repo: 'candy-crush-saga'
        version: '1.300.0.2'
        bundle: false
        filename: 'candy-crush-saga.apk'
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: a
        path: candy-crush-saga.apk
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm candy-crush-saga.apk
