name: get coc_release
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: 'a版本号'
        required: false
        default: 'alpine:latest'  #

jobs:
  pull_and_package:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: Yakov5776/gh-apkmirror-dl@v1.3
        with:
          org: 'supercell'
          repo: 'clash-of-clans'
          version: '17.126.6'
          bundle: false
          filename: 'clash-of-clans.apk'
      - name: Upload Docker images as release assets
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: DockerTarBuilder-ARM64
          files: coc.zip
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
