name: get rm
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: 'a版本号'
        required: false
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: Yakov5776/gh-apkmirror-dl@v1.3
      with:
        org: 'dream-games-ltd-2'
        repo: 'royal-match'
        version: '26821'
        bundle: true
        filename: 'royal-match.apk'
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: a
        path: royal-match.apk
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm royal-match.apk
